#Configurando conexao com o banco

#URL de conexao com o banco
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projetoapirest?createDatabaseIfNotExist=true
#Configurando usuário e senha
    username: root
    password: 2403
#Configurando para gerar logs de consultas no banco   
  jpa:
    show-sql: true
#O MYSQL tem varias versoes de dialeto e por padrao o spring usa uma versao que nao tem chaves estrangeiras por esse motivo e necessario fazer a configuracao abaixo
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect